# Generated by Django 4.0.3 on 2022-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField(null=True)),
                ('marks', models.IntegerField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
