# Generated by Django 4.0.3 on 2022-03-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='grade',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='marks',
            field=models.IntegerField(default=None),
        ),
    ]
