# Generated by Django 4.0.3 on 2022-03-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_studentdb_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
