# Generated by Django 4.0.3 on 2022-03-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_alter_studentdb_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
