# Generated by Django 4.0.3 on 2022-03-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_alter_studentdb_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
