# Generated by Django 4.0.3 on 2022-03-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_alter_studentdb_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='marks',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
